# HA mode with autoscaling
# https://artifacthub.io/packages/helm/argo/argo-cd
redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

configs:
  params:
    server.insecure: true
  cm:
    # Global Kustomize options
    kustomize.buildOptions: "--enable-helm --load-restrictor=LoadRestrictionsNone"
