apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  # goTemplateOptions: ["missingkey=zero"]
  generators:
    - git:
        repoURL: https://github.com/mawi001/scaling-octo-system.git
        revision: main
        files:
        - path: "apps/**/overlays/piew/config.yml"
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  syncPolicy:
    # if app gets deleted by appset then resources are preserved
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}'
    spec:
      # The project the application belongs to.
      project: apps
      # Source of the application manifests
      source:
        repoURL: https://github.com/mawi001/scaling-octo-system.git
        targetRevision: HEAD
        path: '{{.path.path}}'

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'

      # Sync policy
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

  # TODO: replace with improved logic to set annotations per app as done in platform.yml. Requires moving image info from config.yml to here.
  templatePatch: |
    {{- if .annotations}}
    metadata:
      annotations:
      {{- range $annotate := .annotations }}
        {{ $annotate }}
      {{- end }}
    {{- end }}
